# These are the API requests used to test the backend 

@baseUrl = http://localhost:8080

#**********************
# *** DOG *** 
#**********************

#----------------------
# CREATE a new Dog 
//      -> receive POST method on /dogs 
//      + Json data representing a DogRequest Object
#----------------------
###
POST {{baseUrl}}/dogs HTTP/1.1
Content-Type: application/json

  {
    "owner": "681dc7ce9b5a55eaf9924521",
    "name": "Blublubli",
    "age": 3,
    "breed": "Braque"
  }
###

#----------------------
# READ: Get ALL Dogs from the Dog Collection 
//      -> receive GET method on /dogs
#----------------------
###
GET {{baseUrl}}/dogs
Content-Type: application/json
###

#----------------------
# READ: Get a SINGLE Dog from the dog Collection 
//      -> receive GET method on /dogs/{id} 
#----------------------
###
@read_dog_id=6816404642b784266124d516

GET {{baseUrl}}/dogs/{{read_dog_id}}
Content-Type: application/json
###


#----------------------
// UPDATE: Update specific Dog
//        receive PUT method on /dogs/{id} 
//        + a Json data representing a DogUpdateRequest Object
#----------------------
###
@dog_update_id=6812a58d89fd46e7bc07c6
//68124a7c0f0bb4d8a0db6572
PUT {{baseUrl}}/dogs/{{dog_update_id}} HTTP/1.1
Content-Type: application/json

  {
    //owner is a required field, the others are optional
    "owner": "",
    // "name": "Charlie",
    "age": 6,
    "breed": "Braque"
  }
// remmenber : last line cannot have comma in it !
###

#----------------------
# DELETE: a specific Dog
//        -> receive DELETE method on /dogs/{id}
#----------------------
###
@dog_remove_id=6816405d42b784266124d518   

DELETE {{baseUrl}}/dogs/{{dog_remove_id}} HTTP/1.1
Content-Type: application/json
###
